name: ecovery_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  freezed_annotation: ^2.3.2
  json_annotation: ^4.9.0
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
